async_uploader/config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:new, :create]
  get '/photos/new_multiple', to: 'photos#new_multiple', as: :new_photo_multiple
  root to: 'photos#new'

end

async_uploader/app/models/photo.rb
class Photo < ActiveRecord::Base
	dragonfly_accessor :image

	validates :image, presence: true
	validates_size_of :image, maximum: 500.kilobytes, 
					message: 'Should be no more than 500kb', if: :image_changed?
	validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false, message: 'Should be either .jpeg, .jpg, .png, .bmp', if: :image_changed?
					
	
end

async_uploader/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

async_uploader/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def new 
		@photos = Photo.order('created_at DESC')
		@photo = Photo.new
	end

	def create
		respond_to do |format|	
			@photo = Photo.new(photo_params)
			@photo.save
			format.html {redirect_to new_photo_path}
			format.js 
		end	
	end

	def new_multiple
		@photos = Photo.order('created_at DESC')
		@photo = Photo.new
	end

	def photo_params
		params.require(:photo).permit(:image, :title, :author)
	end
end

async_uploader/app/helpers/application_helper.rb
module ApplicationHelper
end

async_uploader/app/helpers/photos_helper.rb
module PhotosHelper
end

async_uploader/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AsyncUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<div class="navbar navbar=inverse", role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=" .navbar-collapse"> 
						<span class="sr-only">Toggle Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to 'Uploader', root_path, class: 'navbar-brand' %>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to 'Upload one', root_path %></li>
						<li><%= link_to 'Upload multiple photos', new_photo_multiple_path %></li>
					</ul>
				</div>
			</div>

<div class="container">

<%= yield %>

</div>

</body>
</html>

async_uploader/app/views/photos/_photo.html.erb
<li class="col-xs-3">
	  <%= link_to image_tag(photo.image.thumb('180x180#').url, alt: photo.title, class: 'img-thumbnail'),
		  	photo.image.remote_url, target: '_blank' %>
	  <% if photo.title.present? %>
	  	<p><%=photo.title%></p>
	  <% end %>

	  <% if photo.author.present? %>
	  <p><b>Author:</b> <%= photo.author %></p>
	  <% end %>
</li> 

async_uploader/app/views/photos/create.js.erb
<% if @photo.new_record? %>
alert('The photo could not be uploaded: <%= j @photo.errors.full_messages.join(', ').html_safe %>');
<% else %>
$('#photos-list').prepend('<%= j render @photo %>');
<% end %>

async_uploader/app/views/photos/new.html.erb
<h1>List Of Photos</h1>

	<ul class="row" id='photos-list'>
		<%=render @photos %>
	</ul>
	<h3>Upload one photo</h3>
	<%=form_for @photo, remote: true do |f| %>
	<div class="form-group">
		<%= f.label :author %>
		<%= f.text_field :author, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image, required: true %>
	</div> 

		<%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
	</div>
	
<% end %>

async_uploader/app/views/photos/new_multiple.html.erb
<h1>List of photos</h1>

<ul class="row" id="photos-list">
  <%= render @photos %>
</ul>

<h3>Upload multiple photos</h3>
<div id="dropzone" class="fade">Drop files here</div>

<%= form_for @photo do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image, 'Choose files here' %>
    <%= f.file_field :image, required: true, multiple: true, name: 'photo[image]' %>
  </div>

  <div class="progress-wrapper">
    <p>Bitrate: <span class="bitrate"></span></p>
    <div class="progress">
      <div class="progress-bar" role="progressbar">
        0%
      </div>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    var multiple_photos_form = $('#new_photo');
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var bitrate = wrapper.find('.bitrate');
    var progress_bar = wrapper.find('.progress-bar');
    multiple_photos_form.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'),
      add: function (e, data) {
        types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
        }
        else { alert(file.name + " must be GIF, JPEG, BMP or PNG file"); }
      }
    });
    multiple_photos_form.on('fileuploadstart', function() {
      wrapper.show();
    });
    multiple_photos_form.on('fileuploaddone', function() {
      wrapper.hide();
      progress_bar.width(0);
    });
    multiple_photos_form.on('fileuploadsubmit', function (e, data) {
      data.formData = {'photo[author]': $('#photo_author').val()};
    });
    multiple_photos_form.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });
    $(document).bind('dragover', function (e) {
      var dropZone = $('#dropzone'),
              timeout = window.dropZoneTimeout;
      if (!timeout) {
        dropZone.addClass('in');
      } else {
        clearTimeout(timeout);
      }
      var found = false,
              node = e.target;
      do {
        if (node === dropZone[0]) {
          found = true;
          break;
        }
        node = node.parentNode;
      } while (node != null);
      if (found) {
        dropZone.addClass('hover');
      } else {
        dropZone.removeClass('hover');
      }
      window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
      }, 100);
    });
  });
</script>
<!-- #Check if each file has correct formatm if yes submit using user submit -->